### ISSUE TITLE
property injection bug

### ISSUE THREAD

**Issue by digitalkaoz** [KnisterPeter/tsdi#121]
```ts
import {Component, Inject, TSDI} from 'tsdi'

const myfunc = () => {
  return () => 'foo'
}

@Component()
class Foo {

  constructor (@Inject('func') public func: Function) {}
}

const c = new TSDI()
c.enableComponentScanner();
c.addProperty('foo', myfunc())

console.log(c.get(Foo).func())
```

throws 

```
node_modules/tsdi/lib/decorators.ts:194
        const factoryMetadata = metadata as FactoryMetadata;
              ^
TypeError: Cannot read property 'rtti' of undefined
    at TSDI.getOrCreate (node_modules/tsdi/lib/decorators.ts:194:15)
    at node_modules/tsdi/lib/decorators.ts:180:28
    at Array.map (native)
    at TSDI.getConstructorParameters (node_modules/tsdi/lib/decorators.ts:180:10)
    at TSDI.getOrCreate (node_modules/tsdi/lib/decorators.ts:201:24)
    at TSDI.get (node_modules/tsdi/lib/decorators.ts:255:2)
```

its line `127` in the transpiled JS file...dont know whats wrong here...

its injected as property because the DIC lacks support for registering non-constructables.
but the real problem seems to be that its a *ready* instance.

i think this could be fixed if we have `TSDI.addInstance(name : string, instance: Constructable|Function)` or `register` accepts already setup instances of something.

**Comment by KnisterPeter** [comment]
For non-construables a factory would be a better solution.
Take this as example:

```typescript
@Component()
class FooFactory {
  @Factory({name: 'FooComponent'})
  public createFooComponent(): () => string {
    return () => 'foo';
  }
}


@Component('Service')
export class Service {

  @Inject('FooComponent')
  private watcher: () => string;

}

```
This should do the trick.
